#pragma checksum "Instructors.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0B7C0E87198DBE80075757A378BF34BEDF884F4D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Windows.Themes;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// Instructors
    /// </summary>
    public partial class Instructors : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 27 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Close;
        
        #line default
        #line hidden
        
        
        #line 52 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Min;
        
        #line default
        #line hidden
        
        /// <summary>
        /// grdcontent Name Field
        /// </summary>
        
        #line 83 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        public System.Windows.Controls.Grid grdcontent;
        
        #line default
        #line hidden
        
        
        #line 85 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Home;
        
        #line default
        #line hidden
        
        
        #line 103 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgHome;
        
        #line default
        #line hidden
        
        
        #line 104 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblHome;
        
        #line default
        #line hidden
        
        
        #line 110 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid bdrContent;
        
        #line default
        #line hidden
        
        
        #line 111 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl tabControl;
        
        #line default
        #line hidden
        
        
        #line 117 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdInstructor;
        
        #line default
        #line hidden
        
        /// <summary>
        /// ins_id Name Field
        /// </summary>
        
        #line 126 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        public System.Windows.Controls.TextBlock ins_id;
        
        #line default
        #line hidden
        
        
        #line 130 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrTitle;
        
        #line default
        #line hidden
        
        
        #line 132 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TitleT;
        
        #line default
        #line hidden
        
        
        #line 136 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrFname;
        
        #line default
        #line hidden
        
        
        #line 138 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FnameT;
        
        #line default
        #line hidden
        
        
        #line 142 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrMname;
        
        #line default
        #line hidden
        
        
        #line 144 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MnameT;
        
        #line default
        #line hidden
        
        
        #line 148 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrLname;
        
        #line default
        #line hidden
        
        
        #line 150 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LnameT;
        
        #line default
        #line hidden
        
        
        #line 156 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrStreet;
        
        #line default
        #line hidden
        
        
        #line 158 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddressT;
        
        #line default
        #line hidden
        
        
        #line 162 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblCon;
        
        #line default
        #line hidden
        
        
        #line 163 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrContact;
        
        #line default
        #line hidden
        
        
        #line 165 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ContactT;
        
        #line default
        #line hidden
        
        
        #line 171 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image image1;
        
        #line default
        #line hidden
        
        
        #line 172 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image image2;
        
        #line default
        #line hidden
        
        
        #line 181 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dtIns;
        
        #line default
        #line hidden
        
        
        #line 187 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn CheckBox_Col;
        
        #line default
        #line hidden
        
        
        #line 336 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkAll;
        
        #line default
        #line hidden
        
        
        #line 339 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCreate;
        
        #line default
        #line hidden
        
        
        #line 367 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpdate;
        
        #line default
        #line hidden
        
        
        #line 395 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDelete;
        
        #line default
        #line hidden
        
        
        #line 435 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dtAcc;
        
        #line default
        #line hidden
        
        
        #line 441 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn CheckBox_Act;
        
        #line default
        #line hidden
        
        
        #line 555 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAccAdd;
        
        #line default
        #line hidden
        
        
        #line 584 "Instructors.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAccDelete;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/instructors.xaml", System.UriKind.Relative);
            
            #line 1 "Instructors.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_Close = ((System.Windows.Controls.Button)(target));
            
            #line 27 "Instructors.xaml"
            this.btn_Close.Click += new System.Windows.RoutedEventHandler(this.Btn_Close_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btn_Min = ((System.Windows.Controls.Button)(target));
            
            #line 52 "Instructors.xaml"
            this.btn_Min.Click += new System.Windows.RoutedEventHandler(this.BtnMin_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.grdcontent = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.btn_Home = ((System.Windows.Controls.Button)(target));
            
            #line 85 "Instructors.xaml"
            this.btn_Home.Click += new System.Windows.RoutedEventHandler(this.Btn_Home_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.imgHome = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.tblHome = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.bdrContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.tabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 9:
            this.grdInstructor = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.ins_id = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.bdrTitle = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.TitleT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.bdrFname = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.FnameT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.bdrMname = ((System.Windows.Controls.Border)(target));
            return;
            case 16:
            this.MnameT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.bdrLname = ((System.Windows.Controls.Border)(target));
            return;
            case 18:
            this.LnameT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.bdrStreet = ((System.Windows.Controls.Border)(target));
            return;
            case 20:
            this.AddressT = ((System.Windows.Controls.TextBox)(target));
            
            #line 158 "Instructors.xaml"
            this.AddressT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.AddressT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 21:
            this.tblCon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.bdrContact = ((System.Windows.Controls.Border)(target));
            return;
            case 23:
            this.ContactT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.image1 = ((System.Windows.Controls.Image)(target));
            return;
            case 25:
            this.image2 = ((System.Windows.Controls.Image)(target));
            return;
            case 26:
            this.dtIns = ((System.Windows.Controls.DataGrid)(target));
            
            #line 181 "Instructors.xaml"
            this.dtIns.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DtIns_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 27:
            this.CheckBox_Col = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 29:
            this.chkAll = ((System.Windows.Controls.CheckBox)(target));
            
            #line 336 "Instructors.xaml"
            this.chkAll.Click += new System.Windows.RoutedEventHandler(this.ChkAll_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.btnCreate = ((System.Windows.Controls.Button)(target));
            
            #line 340 "Instructors.xaml"
            this.btnCreate.Click += new System.Windows.RoutedEventHandler(this.BtnCreate_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            
            #line 368 "Instructors.xaml"
            this.btnUpdate.Click += new System.Windows.RoutedEventHandler(this.BtnUpdate_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.btnDelete = ((System.Windows.Controls.Button)(target));
            
            #line 396 "Instructors.xaml"
            this.btnDelete.Click += new System.Windows.RoutedEventHandler(this.BtnDelete_Click);
            
            #line default
            #line hidden
            return;
            case 33:
            this.dtAcc = ((System.Windows.Controls.DataGrid)(target));
            
            #line 436 "Instructors.xaml"
            this.dtAcc.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DtAcc_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 34:
            this.CheckBox_Act = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 35:
            this.btnAccAdd = ((System.Windows.Controls.Button)(target));
            
            #line 556 "Instructors.xaml"
            this.btnAccAdd.Click += new System.Windows.RoutedEventHandler(this.BtnAccAdd_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.btnAccDelete = ((System.Windows.Controls.Button)(target));
            
            #line 585 "Instructors.xaml"
            this.btnAccDelete.Click += new System.Windows.RoutedEventHandler(this.BtnAccDelete_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 28:
            
            #line 190 "Instructors.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Checked += new System.Windows.RoutedEventHandler(this.CheckBox_Checked);
            
            #line default
            #line hidden
            
            #line 190 "Instructors.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Unchecked += new System.Windows.RoutedEventHandler(this.CheckBox_Unchecked);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

