#pragma checksum "Main.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1E56FF702BAF0739B35C8B53A23334EF503D4644"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WpfApp1 {
    
    
    /// <summary>
    /// Main
    /// </summary>
    public partial class Main : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 61 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Close;
        
        #line default
        #line hidden
        
        
        #line 86 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Min;
        
        #line default
        #line hidden
        
        
        #line 120 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_ins;
        
        #line default
        #line hidden
        
        
        #line 154 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_sub;
        
        #line default
        #line hidden
        
        
        #line 189 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_osub;
        
        #line default
        #line hidden
        
        
        #line 229 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_cour;
        
        #line default
        #line hidden
        
        
        #line 266 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_room;
        
        #line default
        #line hidden
        
        
        #line 301 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_user;
        
        #line default
        #line hidden
        
        
        #line 336 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_sy;
        
        #line default
        #line hidden
        
        
        #line 376 "Main.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_print;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/main.xaml", System.UriKind.Relative);
            
            #line 1 "Main.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_Close = ((System.Windows.Controls.Button)(target));
            
            #line 61 "Main.xaml"
            this.btn_Close.Click += new System.Windows.RoutedEventHandler(this.Btn_Close_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btn_Min = ((System.Windows.Controls.Button)(target));
            
            #line 86 "Main.xaml"
            this.btn_Min.Click += new System.Windows.RoutedEventHandler(this.Btn_Min_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btn_ins = ((System.Windows.Controls.Button)(target));
            
            #line 120 "Main.xaml"
            this.btn_ins.Click += new System.Windows.RoutedEventHandler(this.Btn_ins_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btn_sub = ((System.Windows.Controls.Button)(target));
            
            #line 154 "Main.xaml"
            this.btn_sub.Click += new System.Windows.RoutedEventHandler(this.Btn_sub_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btn_osub = ((System.Windows.Controls.Button)(target));
            
            #line 189 "Main.xaml"
            this.btn_osub.Click += new System.Windows.RoutedEventHandler(this.Btn_osub_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btn_cour = ((System.Windows.Controls.Button)(target));
            
            #line 229 "Main.xaml"
            this.btn_cour.Click += new System.Windows.RoutedEventHandler(this.Btn_cour_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.btn_room = ((System.Windows.Controls.Button)(target));
            
            #line 266 "Main.xaml"
            this.btn_room.Click += new System.Windows.RoutedEventHandler(this.Btn_room_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.btn_user = ((System.Windows.Controls.Button)(target));
            
            #line 301 "Main.xaml"
            this.btn_user.Click += new System.Windows.RoutedEventHandler(this.Btn_user_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btn_sy = ((System.Windows.Controls.Button)(target));
            
            #line 336 "Main.xaml"
            this.btn_sy.Click += new System.Windows.RoutedEventHandler(this.Btn_sy_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btn_print = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

