#pragma checksum "mCourse.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "982A7DD51260980ABF15E3834AD12398B36985D9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// mCourse
    /// </summary>
    public partial class mCourse : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 66 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Main_Grid;
        
        #line default
        #line hidden
        
        
        #line 71 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCcode;
        
        #line default
        #line hidden
        
        
        #line 73 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CcodeT;
        
        #line default
        #line hidden
        
        
        #line 79 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCdesc;
        
        #line default
        #line hidden
        
        
        #line 81 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CdescT;
        
        #line default
        #line hidden
        
        
        #line 86 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tbYr;
        
        #line default
        #line hidden
        
        
        #line 87 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrYr;
        
        #line default
        #line hidden
        
        
        #line 90 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox yrT;
        
        #line default
        #line hidden
        
        
        #line 92 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ScrollBar scrollyr;
        
        #line default
        #line hidden
        
        
        #line 315 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 355 "mCourse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/mcourse.xaml", System.UriKind.Relative);
            
            #line 1 "mCourse.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Main_Grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.bdrCcode = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.CcodeT = ((System.Windows.Controls.TextBox)(target));
            
            #line 74 "mCourse.xaml"
            this.CcodeT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.LetterOnly);
            
            #line default
            #line hidden
            
            #line 74 "mCourse.xaml"
            this.CcodeT.GotFocus += new System.Windows.RoutedEventHandler(this.CcodeT_GotFocus);
            
            #line default
            #line hidden
            
            #line 74 "mCourse.xaml"
            this.CcodeT.LostFocus += new System.Windows.RoutedEventHandler(this.CcodeT_LostFocus);
            
            #line default
            #line hidden
            
            #line 74 "mCourse.xaml"
            this.CcodeT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.CcodeT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.bdrCdesc = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.CdescT = ((System.Windows.Controls.TextBox)(target));
            
            #line 82 "mCourse.xaml"
            this.CdescT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.CdescT_TextChanged);
            
            #line default
            #line hidden
            
            #line 82 "mCourse.xaml"
            this.CdescT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.LetterOnly);
            
            #line default
            #line hidden
            
            #line 82 "mCourse.xaml"
            this.CdescT.GotFocus += new System.Windows.RoutedEventHandler(this.CdescT_GotFocus);
            
            #line default
            #line hidden
            
            #line 82 "mCourse.xaml"
            this.CdescT.LostFocus += new System.Windows.RoutedEventHandler(this.CdescT_LostFocus);
            
            #line default
            #line hidden
            return;
            case 6:
            this.tbYr = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.bdrYr = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.yrT = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.scrollyr = ((System.Windows.Controls.Primitives.ScrollBar)(target));
            
            #line 92 "mCourse.xaml"
            this.scrollyr.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.Scrollyr_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 316 "mCourse.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 356 "mCourse.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

