#pragma checksum "mRoom.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "73A2C5A42056C0C3BA73E659369868BF610C6BCF"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// mRoom
    /// </summary>
    public partial class mRoom : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 66 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Main_Grid;
        
        #line default
        #line hidden
        
        
        #line 71 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrRoom;
        
        #line default
        #line hidden
        
        
        #line 73 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RoomT;
        
        #line default
        #line hidden
        
        
        #line 77 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrRoom2;
        
        #line default
        #line hidden
        
        
        #line 79 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RoomT2;
        
        #line default
        #line hidden
        
        
        #line 85 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrType;
        
        #line default
        #line hidden
        
        
        #line 87 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbType;
        
        #line default
        #line hidden
        
        
        #line 265 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCap;
        
        #line default
        #line hidden
        
        
        #line 267 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CapT;
        
        #line default
        #line hidden
        
        
        #line 272 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        
        #line 297 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 323 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image HelpRoom;
        
        #line default
        #line hidden
        
        
        #line 326 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ttRoom;
        
        #line default
        #line hidden
        
        
        #line 331 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image HelpCapacity;
        
        #line default
        #line hidden
        
        
        #line 334 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ttCap;
        
        #line default
        #line hidden
        
        
        #line 338 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image HelpType;
        
        #line default
        #line hidden
        
        
        #line 341 "mRoom.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ttType;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/mroom.xaml", System.UriKind.Relative);
            
            #line 1 "mRoom.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Main_Grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.bdrRoom = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.RoomT = ((System.Windows.Controls.TextBox)(target));
            
            #line 73 "mRoom.xaml"
            this.RoomT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.LetterOnly);
            
            #line default
            #line hidden
            
            #line 74 "mRoom.xaml"
            this.RoomT.GotFocus += new System.Windows.RoutedEventHandler(this.RoomT_GotFocus);
            
            #line default
            #line hidden
            
            #line 74 "mRoom.xaml"
            this.RoomT.LostFocus += new System.Windows.RoutedEventHandler(this.RoomT_LostFocus);
            
            #line default
            #line hidden
            
            #line 74 "mRoom.xaml"
            this.RoomT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RoomT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.bdrRoom2 = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.RoomT2 = ((System.Windows.Controls.TextBox)(target));
            
            #line 79 "mRoom.xaml"
            this.RoomT2.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberOnly);
            
            #line default
            #line hidden
            
            #line 80 "mRoom.xaml"
            this.RoomT2.GotFocus += new System.Windows.RoutedEventHandler(this.RoomT2_GotFocus);
            
            #line default
            #line hidden
            
            #line 80 "mRoom.xaml"
            this.RoomT2.LostFocus += new System.Windows.RoutedEventHandler(this.RoomT2_LostFocus);
            
            #line default
            #line hidden
            
            #line 80 "mRoom.xaml"
            this.RoomT2.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RoomT2_TextChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.bdrType = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.cbType = ((System.Windows.Controls.ComboBox)(target));
            
            #line 87 "mRoom.xaml"
            this.cbType.GotFocus += new System.Windows.RoutedEventHandler(this.CbType_GotFocus);
            
            #line default
            #line hidden
            
            #line 87 "mRoom.xaml"
            this.cbType.LostFocus += new System.Windows.RoutedEventHandler(this.CbType_LostFocus);
            
            #line default
            #line hidden
            
            #line 88 "mRoom.xaml"
            this.cbType.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbType_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.bdrCap = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.CapT = ((System.Windows.Controls.TextBox)(target));
            
            #line 267 "mRoom.xaml"
            this.CapT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberOnly);
            
            #line default
            #line hidden
            
            #line 268 "mRoom.xaml"
            this.CapT.GotFocus += new System.Windows.RoutedEventHandler(this.CapT_GotFocus);
            
            #line default
            #line hidden
            
            #line 268 "mRoom.xaml"
            this.CapT.LostFocus += new System.Windows.RoutedEventHandler(this.CapT_LostFocus);
            
            #line default
            #line hidden
            
            #line 268 "mRoom.xaml"
            this.CapT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.CapT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 273 "mRoom.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 298 "mRoom.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.HelpRoom = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.ttRoom = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.HelpCapacity = ((System.Windows.Controls.Image)(target));
            return;
            case 15:
            this.ttCap = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.HelpType = ((System.Windows.Controls.Image)(target));
            return;
            case 17:
            this.ttType = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

