#pragma checksum "mSubL.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "759D8CAB40871F6320074161E8B5E5F4752FAF91"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Windows.Themes;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// mSubL
    /// </summary>
    public partial class mSubL : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 74 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrS_code;
        
        #line default
        #line hidden
        
        
        #line 76 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox S_codeT;
        
        #line default
        #line hidden
        
        
        #line 81 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrS_desc;
        
        #line default
        #line hidden
        
        
        #line 83 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox S_descT;
        
        #line default
        #line hidden
        
        
        #line 88 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCourse;
        
        #line default
        #line hidden
        
        
        #line 90 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CourseT;
        
        #line default
        #line hidden
        
        
        #line 302 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrYear;
        
        #line default
        #line hidden
        
        
        #line 304 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox YearT;
        
        #line default
        #line hidden
        
        
        #line 465 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrSemester;
        
        #line default
        #line hidden
        
        
        #line 467 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SemT;
        
        #line default
        #line hidden
        
        
        #line 627 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrTunits;
        
        #line default
        #line hidden
        
        
        #line 629 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TunitsT;
        
        #line default
        #line hidden
        
        
        #line 634 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCUlec;
        
        #line default
        #line hidden
        
        
        #line 641 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CUlecT;
        
        #line default
        #line hidden
        
        
        #line 643 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ScrollBar scrollUnitLec;
        
        #line default
        #line hidden
        
        
        #line 868 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCUlab;
        
        #line default
        #line hidden
        
        
        #line 871 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CUlabT;
        
        #line default
        #line hidden
        
        
        #line 873 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ScrollBar scrollUnitLab;
        
        #line default
        #line hidden
        
        
        #line 1099 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrChours;
        
        #line default
        #line hidden
        
        
        #line 1101 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ChoursT;
        
        #line default
        #line hidden
        
        
        #line 1106 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCHlec;
        
        #line default
        #line hidden
        
        
        #line 1109 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CHlecT;
        
        #line default
        #line hidden
        
        
        #line 1111 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ScrollBar scrollhourLec;
        
        #line default
        #line hidden
        
        
        #line 1336 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCHlab;
        
        #line default
        #line hidden
        
        
        #line 1339 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CHlabT;
        
        #line default
        #line hidden
        
        
        #line 1341 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ScrollBar scrollhourLab;
        
        #line default
        #line hidden
        
        
        #line 1569 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 1597 "mSubL.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/msubl.xaml", System.UriKind.Relative);
            
            #line 1 "mSubL.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.bdrS_code = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.S_codeT = ((System.Windows.Controls.TextBox)(target));
            
            #line 76 "mSubL.xaml"
            this.S_codeT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.LetterNumber);
            
            #line default
            #line hidden
            
            #line 76 "mSubL.xaml"
            this.S_codeT.GotFocus += new System.Windows.RoutedEventHandler(this.S_codeT_GotFocus);
            
            #line default
            #line hidden
            
            #line 76 "mSubL.xaml"
            this.S_codeT.LostFocus += new System.Windows.RoutedEventHandler(this.S_codeT_LostFocus);
            
            #line default
            #line hidden
            
            #line 76 "mSubL.xaml"
            this.S_codeT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.S_codeT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.bdrS_desc = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.S_descT = ((System.Windows.Controls.TextBox)(target));
            
            #line 83 "mSubL.xaml"
            this.S_descT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.LetterNumber);
            
            #line default
            #line hidden
            
            #line 83 "mSubL.xaml"
            this.S_descT.GotFocus += new System.Windows.RoutedEventHandler(this.S_descT_GotFocus);
            
            #line default
            #line hidden
            
            #line 83 "mSubL.xaml"
            this.S_descT.LostFocus += new System.Windows.RoutedEventHandler(this.S_descT_LostFocus);
            
            #line default
            #line hidden
            
            #line 83 "mSubL.xaml"
            this.S_descT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.S_descT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.bdrCourse = ((System.Windows.Controls.Border)(target));
            return;
            case 6:
            this.CourseT = ((System.Windows.Controls.ComboBox)(target));
            
            #line 90 "mSubL.xaml"
            this.CourseT.GotFocus += new System.Windows.RoutedEventHandler(this.CourseT_GotFocus);
            
            #line default
            #line hidden
            
            #line 91 "mSubL.xaml"
            this.CourseT.LostFocus += new System.Windows.RoutedEventHandler(this.CourseT_LostFocus);
            
            #line default
            #line hidden
            
            #line 91 "mSubL.xaml"
            this.CourseT.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CourseT_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.bdrYear = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.YearT = ((System.Windows.Controls.ComboBox)(target));
            
            #line 304 "mSubL.xaml"
            this.YearT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.LetterOnly);
            
            #line default
            #line hidden
            
            #line 304 "mSubL.xaml"
            this.YearT.GotFocus += new System.Windows.RoutedEventHandler(this.YearT_GotFocus);
            
            #line default
            #line hidden
            
            #line 304 "mSubL.xaml"
            this.YearT.LostFocus += new System.Windows.RoutedEventHandler(this.YearT_LostFocus);
            
            #line default
            #line hidden
            
            #line 305 "mSubL.xaml"
            this.YearT.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.YearT_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.bdrSemester = ((System.Windows.Controls.Border)(target));
            return;
            case 10:
            this.SemT = ((System.Windows.Controls.ComboBox)(target));
            
            #line 467 "mSubL.xaml"
            this.SemT.GotFocus += new System.Windows.RoutedEventHandler(this.SemT_GotFocus);
            
            #line default
            #line hidden
            
            #line 467 "mSubL.xaml"
            this.SemT.LostFocus += new System.Windows.RoutedEventHandler(this.SemT_LostFocus);
            
            #line default
            #line hidden
            
            #line 467 "mSubL.xaml"
            this.SemT.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SemT_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.bdrTunits = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.TunitsT = ((System.Windows.Controls.TextBox)(target));
            
            #line 629 "mSubL.xaml"
            this.TunitsT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TunitsT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.bdrCUlec = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.CUlecT = ((System.Windows.Controls.TextBox)(target));
            
            #line 641 "mSubL.xaml"
            this.CUlecT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberOnly);
            
            #line default
            #line hidden
            return;
            case 15:
            this.scrollUnitLec = ((System.Windows.Controls.Primitives.ScrollBar)(target));
            
            #line 643 "mSubL.xaml"
            this.scrollUnitLec.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.ScrollUnitLec_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            this.bdrCUlab = ((System.Windows.Controls.Border)(target));
            return;
            case 17:
            this.CUlabT = ((System.Windows.Controls.TextBox)(target));
            
            #line 871 "mSubL.xaml"
            this.CUlabT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberOnly);
            
            #line default
            #line hidden
            return;
            case 18:
            this.scrollUnitLab = ((System.Windows.Controls.Primitives.ScrollBar)(target));
            
            #line 873 "mSubL.xaml"
            this.scrollUnitLab.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.ScrollUnitLab_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 19:
            this.bdrChours = ((System.Windows.Controls.Border)(target));
            return;
            case 20:
            this.ChoursT = ((System.Windows.Controls.TextBox)(target));
            
            #line 1101 "mSubL.xaml"
            this.ChoursT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.ChoursT_TextChanged);
            
            #line default
            #line hidden
            return;
            case 21:
            this.bdrCHlec = ((System.Windows.Controls.Border)(target));
            return;
            case 22:
            this.CHlecT = ((System.Windows.Controls.TextBox)(target));
            
            #line 1109 "mSubL.xaml"
            this.CHlecT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberOnly);
            
            #line default
            #line hidden
            return;
            case 23:
            this.scrollhourLec = ((System.Windows.Controls.Primitives.ScrollBar)(target));
            
            #line 1111 "mSubL.xaml"
            this.scrollhourLec.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.ScrollhourLec_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 24:
            this.bdrCHlab = ((System.Windows.Controls.Border)(target));
            return;
            case 25:
            this.CHlabT = ((System.Windows.Controls.TextBox)(target));
            
            #line 1340 "mSubL.xaml"
            this.CHlabT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberOnly);
            
            #line default
            #line hidden
            return;
            case 26:
            this.scrollhourLab = ((System.Windows.Controls.Primitives.ScrollBar)(target));
            
            #line 1341 "mSubL.xaml"
            this.scrollhourLab.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.ScrollhourLab_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 27:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 1570 "mSubL.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 1597 "mSubL.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

