#pragma checksum "Sub_List.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "981277340E21F816229CA26C445C7EE89368D7EF"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WpfApp1 {
    
    
    /// <summary>
    /// Sub_List
    /// </summary>
    public partial class Sub_List : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 26 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Close;
        
        #line default
        #line hidden
        
        
        #line 51 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Min;
        
        #line default
        #line hidden
        
        /// <summary>
        /// grdcontent Name Field
        /// </summary>
        
        #line 82 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        public System.Windows.Controls.Grid grdcontent;
        
        #line default
        #line hidden
        
        
        #line 84 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Home;
        
        #line default
        #line hidden
        
        
        #line 102 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgHome;
        
        #line default
        #line hidden
        
        
        #line 103 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblHome;
        
        #line default
        #line hidden
        
        
        #line 109 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid bdrContent;
        
        #line default
        #line hidden
        
        
        #line 116 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdSubject;
        
        #line default
        #line hidden
        
        
        #line 125 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrS_code;
        
        #line default
        #line hidden
        
        
        #line 127 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock S_codeT;
        
        #line default
        #line hidden
        
        
        #line 131 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrS_desc;
        
        #line default
        #line hidden
        
        
        #line 133 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock S_descT;
        
        #line default
        #line hidden
        
        
        #line 138 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCourse;
        
        #line default
        #line hidden
        
        
        #line 140 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CourseT;
        
        #line default
        #line hidden
        
        
        #line 145 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrYear;
        
        #line default
        #line hidden
        
        
        #line 147 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock YearT;
        
        #line default
        #line hidden
        
        
        #line 152 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrSemester;
        
        #line default
        #line hidden
        
        
        #line 154 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SemT;
        
        #line default
        #line hidden
        
        
        #line 159 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrTunits;
        
        #line default
        #line hidden
        
        
        #line 161 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TunitsT;
        
        #line default
        #line hidden
        
        
        #line 166 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCUlec;
        
        #line default
        #line hidden
        
        
        #line 168 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CUlecT;
        
        #line default
        #line hidden
        
        
        #line 172 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCUlab;
        
        #line default
        #line hidden
        
        
        #line 174 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CUlabT;
        
        #line default
        #line hidden
        
        
        #line 179 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrChours;
        
        #line default
        #line hidden
        
        
        #line 181 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ChoursT;
        
        #line default
        #line hidden
        
        
        #line 186 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCHlec;
        
        #line default
        #line hidden
        
        
        #line 188 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CHlecT;
        
        #line default
        #line hidden
        
        
        #line 192 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCHlab;
        
        #line default
        #line hidden
        
        
        #line 194 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CHlabT;
        
        #line default
        #line hidden
        
        
        #line 204 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dtSub;
        
        #line default
        #line hidden
        
        
        #line 209 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn CheckBox_Col;
        
        #line default
        #line hidden
        
        
        #line 381 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkAll;
        
        #line default
        #line hidden
        
        
        #line 385 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnNew;
        
        #line default
        #line hidden
        
        
        #line 410 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpdate;
        
        #line default
        #line hidden
        
        
        #line 438 "Sub_List.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDelete;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/sub_list.xaml", System.UriKind.Relative);
            
            #line 1 "Sub_List.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_Close = ((System.Windows.Controls.Button)(target));
            
            #line 26 "Sub_List.xaml"
            this.btn_Close.Click += new System.Windows.RoutedEventHandler(this.Btn_Close_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btn_Min = ((System.Windows.Controls.Button)(target));
            
            #line 51 "Sub_List.xaml"
            this.btn_Min.Click += new System.Windows.RoutedEventHandler(this.Btn_Min_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.grdcontent = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.btn_Home = ((System.Windows.Controls.Button)(target));
            
            #line 84 "Sub_List.xaml"
            this.btn_Home.Click += new System.Windows.RoutedEventHandler(this.Btn_Home_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.imgHome = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.tblHome = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.bdrContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.grdSubject = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.bdrS_code = ((System.Windows.Controls.Border)(target));
            return;
            case 10:
            this.S_codeT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.bdrS_desc = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.S_descT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.bdrCourse = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.CourseT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.bdrYear = ((System.Windows.Controls.Border)(target));
            return;
            case 16:
            this.YearT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.bdrSemester = ((System.Windows.Controls.Border)(target));
            return;
            case 18:
            this.SemT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.bdrTunits = ((System.Windows.Controls.Border)(target));
            return;
            case 20:
            this.TunitsT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.bdrCUlec = ((System.Windows.Controls.Border)(target));
            return;
            case 22:
            this.CUlecT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.bdrCUlab = ((System.Windows.Controls.Border)(target));
            return;
            case 24:
            this.CUlabT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.bdrChours = ((System.Windows.Controls.Border)(target));
            return;
            case 26:
            this.ChoursT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.bdrCHlec = ((System.Windows.Controls.Border)(target));
            return;
            case 28:
            this.CHlecT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 29:
            this.bdrCHlab = ((System.Windows.Controls.Border)(target));
            return;
            case 30:
            this.CHlabT = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            this.dtSub = ((System.Windows.Controls.DataGrid)(target));
            
            #line 205 "Sub_List.xaml"
            this.dtSub.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DtSub_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 32:
            this.CheckBox_Col = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 34:
            this.chkAll = ((System.Windows.Controls.CheckBox)(target));
            
            #line 381 "Sub_List.xaml"
            this.chkAll.Click += new System.Windows.RoutedEventHandler(this.ChkAll_Click);
            
            #line default
            #line hidden
            return;
            case 35:
            this.btnNew = ((System.Windows.Controls.Button)(target));
            
            #line 386 "Sub_List.xaml"
            this.btnNew.Click += new System.Windows.RoutedEventHandler(this.BtnNew_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            
            #line 411 "Sub_List.xaml"
            this.btnUpdate.Click += new System.Windows.RoutedEventHandler(this.BtnUpdate_Click);
            
            #line default
            #line hidden
            return;
            case 37:
            this.btnDelete = ((System.Windows.Controls.Button)(target));
            
            #line 438 "Sub_List.xaml"
            this.btnDelete.Click += new System.Windows.RoutedEventHandler(this.BtnDelete_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 33:
            
            #line 212 "Sub_List.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Checked += new System.Windows.RoutedEventHandler(this.CheckBox_Checked);
            
            #line default
            #line hidden
            
            #line 212 "Sub_List.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Unchecked += new System.Windows.RoutedEventHandler(this.CheckBox_Unchecked);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

