#pragma checksum "mAccount.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "334EE120E8DD11FE4D06E2131A38772515D8386A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// mAccount
    /// </summary>
    public partial class mAccount : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 64 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid First_Grid;
        
        #line default
        #line hidden
        
        
        #line 69 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrInstructor;
        
        #line default
        #line hidden
        
        
        #line 72 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbInstructor;
        
        #line default
        #line hidden
        
        
        #line 268 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrUsername;
        
        #line default
        #line hidden
        
        
        #line 271 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UsernameT;
        
        #line default
        #line hidden
        
        
        #line 275 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image UsernameW;
        
        #line default
        #line hidden
        
        
        #line 279 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrPassword;
        
        #line default
        #line hidden
        
        
        #line 282 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PasswordT;
        
        #line default
        #line hidden
        
        
        #line 287 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image PasswordW;
        
        #line default
        #line hidden
        
        
        #line 291 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrConPass;
        
        #line default
        #line hidden
        
        
        #line 294 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox ConPassT;
        
        #line default
        #line hidden
        
        
        #line 298 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ConpassW;
        
        #line default
        #line hidden
        
        
        #line 304 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnNext;
        
        #line default
        #line hidden
        
        
        #line 332 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose1;
        
        #line default
        #line hidden
        
        
        #line 362 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Second_Grid;
        
        #line default
        #line hidden
        
        
        #line 366 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrSecQue;
        
        #line default
        #line hidden
        
        
        #line 373 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbSecQue;
        
        #line default
        #line hidden
        
        
        #line 561 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrAnswer;
        
        #line default
        #line hidden
        
        
        #line 564 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox AnswerT;
        
        #line default
        #line hidden
        
        
        #line 568 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image AnswerW;
        
        #line default
        #line hidden
        
        
        #line 570 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 594 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 621 "mAccount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose2;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/maccount.xaml", System.UriKind.Relative);
            
            #line 1 "mAccount.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.First_Grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.bdrInstructor = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.cbInstructor = ((System.Windows.Controls.ComboBox)(target));
            
            #line 73 "mAccount.xaml"
            this.cbInstructor.GotFocus += new System.Windows.RoutedEventHandler(this.CbInstructor_GotFocus);
            
            #line default
            #line hidden
            
            #line 73 "mAccount.xaml"
            this.cbInstructor.LostFocus += new System.Windows.RoutedEventHandler(this.CbInstructor_LostFocus);
            
            #line default
            #line hidden
            
            #line 73 "mAccount.xaml"
            this.cbInstructor.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbInstructor_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.bdrUsername = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.UsernameT = ((System.Windows.Controls.TextBox)(target));
            
            #line 271 "mAccount.xaml"
            this.UsernameT.GotFocus += new System.Windows.RoutedEventHandler(this.UsernameT_GotFocus);
            
            #line default
            #line hidden
            
            #line 271 "mAccount.xaml"
            this.UsernameT.LostFocus += new System.Windows.RoutedEventHandler(this.UsernameT_LostFocus);
            
            #line default
            #line hidden
            
            #line 272 "mAccount.xaml"
            this.UsernameT.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.UsernameT_TextChanged);
            
            #line default
            #line hidden
            
            #line 272 "mAccount.xaml"
            this.UsernameT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.UsernameT_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 6:
            this.UsernameW = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.bdrPassword = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.PasswordT = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 282 "mAccount.xaml"
            this.PasswordT.GotFocus += new System.Windows.RoutedEventHandler(this.PasswordT_GotFocus);
            
            #line default
            #line hidden
            
            #line 282 "mAccount.xaml"
            this.PasswordT.LostFocus += new System.Windows.RoutedEventHandler(this.PasswordT_LostFocus);
            
            #line default
            #line hidden
            
            #line 283 "mAccount.xaml"
            this.PasswordT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.PasswordT_PreviewTextInput);
            
            #line default
            #line hidden
            
            #line 283 "mAccount.xaml"
            this.PasswordT.PasswordChanged += new System.Windows.RoutedEventHandler(this.PasswordT_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.PasswordW = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.bdrConPass = ((System.Windows.Controls.Border)(target));
            return;
            case 11:
            this.ConPassT = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 294 "mAccount.xaml"
            this.ConPassT.GotFocus += new System.Windows.RoutedEventHandler(this.ConPassT_GotFocus);
            
            #line default
            #line hidden
            
            #line 294 "mAccount.xaml"
            this.ConPassT.LostFocus += new System.Windows.RoutedEventHandler(this.ConPassT_LostFocus);
            
            #line default
            #line hidden
            
            #line 295 "mAccount.xaml"
            this.ConPassT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.ConPassT_PreviewTextInput);
            
            #line default
            #line hidden
            
            #line 295 "mAccount.xaml"
            this.ConPassT.PasswordChanged += new System.Windows.RoutedEventHandler(this.ConPassT_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ConpassW = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.btnNext = ((System.Windows.Controls.Button)(target));
            
            #line 305 "mAccount.xaml"
            this.btnNext.Click += new System.Windows.RoutedEventHandler(this.BtnNext_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.btnClose1 = ((System.Windows.Controls.Button)(target));
            
            #line 333 "mAccount.xaml"
            this.btnClose1.Click += new System.Windows.RoutedEventHandler(this.BtnClose1_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.Second_Grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            this.bdrSecQue = ((System.Windows.Controls.Border)(target));
            return;
            case 17:
            this.cbSecQue = ((System.Windows.Controls.ComboBox)(target));
            
            #line 373 "mAccount.xaml"
            this.cbSecQue.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbSecQue_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 374 "mAccount.xaml"
            this.cbSecQue.GotFocus += new System.Windows.RoutedEventHandler(this.CbSecQue_GotFocus);
            
            #line default
            #line hidden
            
            #line 374 "mAccount.xaml"
            this.cbSecQue.LostFocus += new System.Windows.RoutedEventHandler(this.CbSecQue_LostFocus);
            
            #line default
            #line hidden
            return;
            case 18:
            this.bdrAnswer = ((System.Windows.Controls.Border)(target));
            return;
            case 19:
            this.AnswerT = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 564 "mAccount.xaml"
            this.AnswerT.GotFocus += new System.Windows.RoutedEventHandler(this.AnswerT_GotFocus);
            
            #line default
            #line hidden
            
            #line 565 "mAccount.xaml"
            this.AnswerT.LostFocus += new System.Windows.RoutedEventHandler(this.AnswerT_LostFocus);
            
            #line default
            #line hidden
            
            #line 565 "mAccount.xaml"
            this.AnswerT.PasswordChanged += new System.Windows.RoutedEventHandler(this.AnswerT_PasswordChanged);
            
            #line default
            #line hidden
            
            #line 565 "mAccount.xaml"
            this.AnswerT.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.AnswerT_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 20:
            this.AnswerW = ((System.Windows.Controls.Image)(target));
            return;
            case 21:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            
            #line 571 "mAccount.xaml"
            this.btnBack.Click += new System.Windows.RoutedEventHandler(this.BtnBack_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 595 "mAccount.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.btnClose2 = ((System.Windows.Controls.Button)(target));
            
            #line 622 "mAccount.xaml"
            this.btnClose2.Click += new System.Windows.RoutedEventHandler(this.BtnClose1_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

