#pragma checksum "mIns.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7DFC00E26B587AF2B634014E0DEA85B6166D6193"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// mIns
    /// </summary>
    public partial class mIns : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 66 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Main_Grid;
        
        #line default
        #line hidden
        
        
        #line 71 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrTitle;
        
        #line default
        #line hidden
        
        
        #line 79 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbTitle;
        
        #line default
        #line hidden
        
        
        #line 253 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblTitle;
        
        #line default
        #line hidden
        
        
        #line 267 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrFname;
        
        #line default
        #line hidden
        
        
        #line 271 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FnameT;
        
        #line default
        #line hidden
        
        
        #line 272 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FnameW;
        
        #line default
        #line hidden
        
        
        #line 274 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbxFname;
        
        #line default
        #line hidden
        
        
        #line 296 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblFname;
        
        #line default
        #line hidden
        
        
        #line 301 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrMname;
        
        #line default
        #line hidden
        
        
        #line 305 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MnameT;
        
        #line default
        #line hidden
        
        
        #line 306 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MnameW;
        
        #line default
        #line hidden
        
        
        #line 308 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbxMname;
        
        #line default
        #line hidden
        
        
        #line 331 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblMname;
        
        #line default
        #line hidden
        
        
        #line 336 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrLname;
        
        #line default
        #line hidden
        
        
        #line 340 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LnameT;
        
        #line default
        #line hidden
        
        
        #line 341 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LnameW;
        
        #line default
        #line hidden
        
        
        #line 343 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbxLname;
        
        #line default
        #line hidden
        
        
        #line 366 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblLname;
        
        #line default
        #line hidden
        
        
        #line 373 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrRegion;
        
        #line default
        #line hidden
        
        
        #line 380 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbRegion;
        
        #line default
        #line hidden
        
        
        #line 554 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblRegion;
        
        #line default
        #line hidden
        
        
        #line 568 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrProvince;
        
        #line default
        #line hidden
        
        
        #line 576 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbProvince;
        
        #line default
        #line hidden
        
        
        #line 750 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblProvince;
        
        #line default
        #line hidden
        
        
        #line 767 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrCitmun;
        
        #line default
        #line hidden
        
        
        #line 775 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbCitmun;
        
        #line default
        #line hidden
        
        
        #line 949 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblCitmun;
        
        #line default
        #line hidden
        
        
        #line 966 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrSubmun;
        
        #line default
        #line hidden
        
        
        #line 974 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbSubmun;
        
        #line default
        #line hidden
        
        
        #line 1148 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblSubmun;
        
        #line default
        #line hidden
        
        
        #line 1167 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrBrgy;
        
        #line default
        #line hidden
        
        
        #line 1175 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbBrgy;
        
        #line default
        #line hidden
        
        
        #line 1349 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblBrgy;
        
        #line default
        #line hidden
        
        
        #line 1367 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrStreet;
        
        #line default
        #line hidden
        
        
        #line 1375 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox StreetW;
        
        #line default
        #line hidden
        
        
        #line 1376 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox StreetT;
        
        #line default
        #line hidden
        
        
        #line 1378 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbxStreet;
        
        #line default
        #line hidden
        
        
        #line 1400 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblStreet;
        
        #line default
        #line hidden
        
        
        #line 1407 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrContact;
        
        #line default
        #line hidden
        
        
        #line 1414 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdCon;
        
        #line default
        #line hidden
        
        
        #line 1415 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image conim;
        
        #line default
        #line hidden
        
        
        #line 1416 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock conpre;
        
        #line default
        #line hidden
        
        
        #line 1418 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrConline;
        
        #line default
        #line hidden
        
        
        #line 1420 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ContactW;
        
        #line default
        #line hidden
        
        
        #line 1421 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ContactT;
        
        #line default
        #line hidden
        
        
        #line 1423 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbxContact;
        
        #line default
        #line hidden
        
        
        #line 1444 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ContactWW;
        
        #line default
        #line hidden
        
        
        #line 1447 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblContact;
        
        #line default
        #line hidden
        
        
        #line 1453 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 1478 "mIns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/mins.xaml", System.UriKind.Relative);
            
            #line 1 "mIns.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "mIns.xaml"
            ((WpfApp1.mIns)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.UserControl_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.Main_Grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.bdrTitle = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.cbTitle = ((System.Windows.Controls.ComboBox)(target));
            
            #line 80 "mIns.xaml"
            this.cbTitle.GotFocus += new System.Windows.RoutedEventHandler(this.CbTitle_GotFocus);
            
            #line default
            #line hidden
            
            #line 80 "mIns.xaml"
            this.cbTitle.LostFocus += new System.Windows.RoutedEventHandler(this.CbTitle_LostFocus);
            
            #line default
            #line hidden
            
            #line 80 "mIns.xaml"
            this.cbTitle.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbTitle_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.tblTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.bdrFname = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.FnameT = ((System.Windows.Controls.TextBox)(target));
            
            #line 271 "mIns.xaml"
            this.FnameT.GotFocus += new System.Windows.RoutedEventHandler(this.Fname_GotFocus);
            
            #line default
            #line hidden
            return;
            case 8:
            this.FnameW = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.tbxFname = ((System.Windows.Controls.TextBox)(target));
            
            #line 274 "mIns.xaml"
            this.tbxFname.LostFocus += new System.Windows.RoutedEventHandler(this.TbxFname_LostFocus);
            
            #line default
            #line hidden
            
            #line 275 "mIns.xaml"
            this.tbxFname.GotFocus += new System.Windows.RoutedEventHandler(this.Fname_GotFocus);
            
            #line default
            #line hidden
            
            #line 275 "mIns.xaml"
            this.tbxFname.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TbxFname_TextChanged);
            
            #line default
            #line hidden
            
            #line 275 "mIns.xaml"
            this.tbxFname.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TbxFname_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 10:
            this.tblFname = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.bdrMname = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.MnameT = ((System.Windows.Controls.TextBox)(target));
            
            #line 305 "mIns.xaml"
            this.MnameT.GotFocus += new System.Windows.RoutedEventHandler(this.MnameW_GotFocus);
            
            #line default
            #line hidden
            return;
            case 13:
            this.MnameW = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.tbxMname = ((System.Windows.Controls.TextBox)(target));
            
            #line 309 "mIns.xaml"
            this.tbxMname.LostFocus += new System.Windows.RoutedEventHandler(this.TbxMname_LostFocus);
            
            #line default
            #line hidden
            
            #line 309 "mIns.xaml"
            this.tbxMname.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TbxMname_TextChanged);
            
            #line default
            #line hidden
            
            #line 309 "mIns.xaml"
            this.tbxMname.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TbxMname_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 15:
            this.tblMname = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.bdrLname = ((System.Windows.Controls.Border)(target));
            return;
            case 17:
            this.LnameT = ((System.Windows.Controls.TextBox)(target));
            
            #line 340 "mIns.xaml"
            this.LnameT.GotFocus += new System.Windows.RoutedEventHandler(this.LnameW_GotFocus);
            
            #line default
            #line hidden
            return;
            case 18:
            this.LnameW = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.tbxLname = ((System.Windows.Controls.TextBox)(target));
            
            #line 344 "mIns.xaml"
            this.tbxLname.LostFocus += new System.Windows.RoutedEventHandler(this.TbxLname_LostFocus);
            
            #line default
            #line hidden
            
            #line 344 "mIns.xaml"
            this.tbxLname.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TbxLname_TextChanged);
            
            #line default
            #line hidden
            
            #line 344 "mIns.xaml"
            this.tbxLname.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TbxLname_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 20:
            this.tblLname = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.bdrRegion = ((System.Windows.Controls.Border)(target));
            return;
            case 22:
            this.cbRegion = ((System.Windows.Controls.ComboBox)(target));
            
            #line 380 "mIns.xaml"
            this.cbRegion.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbRegion_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 381 "mIns.xaml"
            this.cbRegion.GotFocus += new System.Windows.RoutedEventHandler(this.CbRegion_GotFocus);
            
            #line default
            #line hidden
            
            #line 381 "mIns.xaml"
            this.cbRegion.LostFocus += new System.Windows.RoutedEventHandler(this.CbRegion_LostFocus);
            
            #line default
            #line hidden
            return;
            case 23:
            this.tblRegion = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.bdrProvince = ((System.Windows.Controls.Border)(target));
            
            #line 569 "mIns.xaml"
            this.bdrProvince.IsEnabledChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.BdrProvince_IsEnabledChanged);
            
            #line default
            #line hidden
            return;
            case 25:
            this.cbProvince = ((System.Windows.Controls.ComboBox)(target));
            
            #line 576 "mIns.xaml"
            this.cbProvince.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbProvince_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 577 "mIns.xaml"
            this.cbProvince.GotFocus += new System.Windows.RoutedEventHandler(this.CbProvince_GotFocus);
            
            #line default
            #line hidden
            
            #line 577 "mIns.xaml"
            this.cbProvince.LostFocus += new System.Windows.RoutedEventHandler(this.CbProvince_LostFocus);
            
            #line default
            #line hidden
            return;
            case 26:
            this.tblProvince = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.bdrCitmun = ((System.Windows.Controls.Border)(target));
            
            #line 767 "mIns.xaml"
            this.bdrCitmun.IsEnabledChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.BdrCitmun_IsEnabledChanged);
            
            #line default
            #line hidden
            return;
            case 28:
            this.cbCitmun = ((System.Windows.Controls.ComboBox)(target));
            
            #line 775 "mIns.xaml"
            this.cbCitmun.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbCitmun_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 776 "mIns.xaml"
            this.cbCitmun.GotFocus += new System.Windows.RoutedEventHandler(this.CbCitmun_GotFocus);
            
            #line default
            #line hidden
            
            #line 776 "mIns.xaml"
            this.cbCitmun.LostFocus += new System.Windows.RoutedEventHandler(this.CbCitmun_LostFocus);
            
            #line default
            #line hidden
            return;
            case 29:
            this.tblCitmun = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.bdrSubmun = ((System.Windows.Controls.Border)(target));
            
            #line 966 "mIns.xaml"
            this.bdrSubmun.IsEnabledChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.BdrSubmun_IsEnabledChanged);
            
            #line default
            #line hidden
            return;
            case 31:
            this.cbSubmun = ((System.Windows.Controls.ComboBox)(target));
            
            #line 974 "mIns.xaml"
            this.cbSubmun.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbSubmun_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 975 "mIns.xaml"
            this.cbSubmun.GotFocus += new System.Windows.RoutedEventHandler(this.CbSubmun_GotFocus);
            
            #line default
            #line hidden
            
            #line 975 "mIns.xaml"
            this.cbSubmun.LostFocus += new System.Windows.RoutedEventHandler(this.CbSubmun_LostFocus);
            
            #line default
            #line hidden
            return;
            case 32:
            this.tblSubmun = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.bdrBrgy = ((System.Windows.Controls.Border)(target));
            
            #line 1167 "mIns.xaml"
            this.bdrBrgy.IsEnabledChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.BdrBrgy_IsEnabledChanged);
            
            #line default
            #line hidden
            return;
            case 34:
            this.cbBrgy = ((System.Windows.Controls.ComboBox)(target));
            
            #line 1175 "mIns.xaml"
            this.cbBrgy.GotFocus += new System.Windows.RoutedEventHandler(this.CbBrgy_GotFocus);
            
            #line default
            #line hidden
            
            #line 1175 "mIns.xaml"
            this.cbBrgy.LostFocus += new System.Windows.RoutedEventHandler(this.CbBrgy_LostFocus);
            
            #line default
            #line hidden
            
            #line 1176 "mIns.xaml"
            this.cbBrgy.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbBrgy_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 35:
            this.tblBrgy = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.bdrStreet = ((System.Windows.Controls.Border)(target));
            return;
            case 37:
            this.StreetW = ((System.Windows.Controls.TextBox)(target));
            
            #line 1375 "mIns.xaml"
            this.StreetW.GotFocus += new System.Windows.RoutedEventHandler(this.StreetW_GotFocus);
            
            #line default
            #line hidden
            return;
            case 38:
            this.StreetT = ((System.Windows.Controls.TextBox)(target));
            
            #line 1376 "mIns.xaml"
            this.StreetT.GotFocus += new System.Windows.RoutedEventHandler(this.StreetW_GotFocus);
            
            #line default
            #line hidden
            return;
            case 39:
            this.tbxStreet = ((System.Windows.Controls.TextBox)(target));
            
            #line 1379 "mIns.xaml"
            this.tbxStreet.LostFocus += new System.Windows.RoutedEventHandler(this.TbxStreet_LostFocus);
            
            #line default
            #line hidden
            
            #line 1379 "mIns.xaml"
            this.tbxStreet.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TbxStreet_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 40:
            this.tblStreet = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 41:
            this.bdrContact = ((System.Windows.Controls.Border)(target));
            return;
            case 42:
            this.grdCon = ((System.Windows.Controls.Grid)(target));
            return;
            case 43:
            this.conim = ((System.Windows.Controls.Image)(target));
            return;
            case 44:
            this.conpre = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 45:
            this.bdrConline = ((System.Windows.Controls.Border)(target));
            return;
            case 46:
            this.ContactW = ((System.Windows.Controls.TextBox)(target));
            
            #line 1420 "mIns.xaml"
            this.ContactW.GotFocus += new System.Windows.RoutedEventHandler(this.ContactW_GotFocus);
            
            #line default
            #line hidden
            return;
            case 47:
            this.ContactT = ((System.Windows.Controls.TextBox)(target));
            
            #line 1421 "mIns.xaml"
            this.ContactT.GotFocus += new System.Windows.RoutedEventHandler(this.ContactW_GotFocus);
            
            #line default
            #line hidden
            return;
            case 48:
            this.tbxContact = ((System.Windows.Controls.TextBox)(target));
            
            #line 1424 "mIns.xaml"
            this.tbxContact.LostFocus += new System.Windows.RoutedEventHandler(this.TbxContact_LostFocus);
            
            #line default
            #line hidden
            
            #line 1424 "mIns.xaml"
            this.tbxContact.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TbxContact_TextChanged);
            
            #line default
            #line hidden
            
            #line 1424 "mIns.xaml"
            this.tbxContact.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TbxContact_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 49:
            this.ContactWW = ((System.Windows.Controls.TextBox)(target));
            
            #line 1444 "mIns.xaml"
            this.ContactWW.GotFocus += new System.Windows.RoutedEventHandler(this.ContactW_GotFocus);
            
            #line default
            #line hidden
            return;
            case 50:
            this.tblContact = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 51:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 1454 "mIns.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 52:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 1479 "mIns.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

