#pragma checksum "OpenSub.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "218D9EB7C752243E9E74B9FA129D23A6E64B6583"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// OpenSub
    /// </summary>
    public partial class OpenSub : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 75 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Close;
        
        #line default
        #line hidden
        
        
        #line 106 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border btn_Min;
        
        #line default
        #line hidden
        
        /// <summary>
        /// grdcontent Name Field
        /// </summary>
        
        #line 144 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        public System.Windows.Controls.Grid grdcontent;
        
        #line default
        #line hidden
        
        
        #line 146 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Home;
        
        #line default
        #line hidden
        
        
        #line 164 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgHome;
        
        #line default
        #line hidden
        
        
        #line 165 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblHome;
        
        #line default
        #line hidden
        
        
        #line 171 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid bdrContent;
        
        #line default
        #line hidden
        
        
        #line 187 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrSearch;
        
        #line default
        #line hidden
        
        
        #line 189 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox S_codeT;
        
        #line default
        #line hidden
        
        
        #line 191 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SearchW;
        
        #line default
        #line hidden
        
        
        #line 194 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrSemester;
        
        #line default
        #line hidden
        
        
        #line 201 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbSemester;
        
        #line default
        #line hidden
        
        
        #line 376 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblSemester;
        
        #line default
        #line hidden
        
        
        #line 390 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrSy;
        
        #line default
        #line hidden
        
        
        #line 397 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbSy;
        
        #line default
        #line hidden
        
        
        #line 571 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblSy;
        
        #line default
        #line hidden
        
        
        #line 589 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dtOpenSub;
        
        #line default
        #line hidden
        
        
        #line 594 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn CheckBox_Col;
        
        #line default
        #line hidden
        
        
        #line 741 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOpen;
        
        #line default
        #line hidden
        
        
        #line 766 "OpenSub.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCloseSub;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/opensub.xaml", System.UriKind.Relative);
            
            #line 1 "OpenSub.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_Close = ((System.Windows.Controls.Button)(target));
            
            #line 75 "OpenSub.xaml"
            this.btn_Close.Click += new System.Windows.RoutedEventHandler(this.Btn_Close_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btn_Min = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.grdcontent = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.btn_Home = ((System.Windows.Controls.Button)(target));
            
            #line 146 "OpenSub.xaml"
            this.btn_Home.Click += new System.Windows.RoutedEventHandler(this.Btn_Home_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.imgHome = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.tblHome = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.bdrContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.bdrSearch = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.S_codeT = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.SearchW = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.bdrSemester = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.cbSemester = ((System.Windows.Controls.ComboBox)(target));
            
            #line 201 "OpenSub.xaml"
            this.cbSemester.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbSemester_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 202 "OpenSub.xaml"
            this.cbSemester.GotFocus += new System.Windows.RoutedEventHandler(this.CbSemester_GotFocus);
            
            #line default
            #line hidden
            
            #line 202 "OpenSub.xaml"
            this.cbSemester.LostFocus += new System.Windows.RoutedEventHandler(this.CbSemester_LostFocus);
            
            #line default
            #line hidden
            return;
            case 13:
            this.tblSemester = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.bdrSy = ((System.Windows.Controls.Border)(target));
            return;
            case 15:
            this.cbSy = ((System.Windows.Controls.ComboBox)(target));
            
            #line 397 "OpenSub.xaml"
            this.cbSy.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CbSy_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 398 "OpenSub.xaml"
            this.cbSy.GotFocus += new System.Windows.RoutedEventHandler(this.CbSy_GotFocus);
            
            #line default
            #line hidden
            
            #line 398 "OpenSub.xaml"
            this.cbSy.LostFocus += new System.Windows.RoutedEventHandler(this.CbSy_LostFocus);
            
            #line default
            #line hidden
            return;
            case 16:
            this.tblSy = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.dtOpenSub = ((System.Windows.Controls.DataGrid)(target));
            
            #line 590 "OpenSub.xaml"
            this.dtOpenSub.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DtOpenSub_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.CheckBox_Col = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 20:
            this.btnOpen = ((System.Windows.Controls.Button)(target));
            
            #line 741 "OpenSub.xaml"
            this.btnOpen.Click += new System.Windows.RoutedEventHandler(this.BtnOpen_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.btnCloseSub = ((System.Windows.Controls.Button)(target));
            
            #line 767 "OpenSub.xaml"
            this.btnCloseSub.Click += new System.Windows.RoutedEventHandler(this.BtnCloseSub_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 19:
            
            #line 597 "OpenSub.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Checked += new System.Windows.RoutedEventHandler(this.CheckBox_Checked);
            
            #line default
            #line hidden
            
            #line 597 "OpenSub.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Unchecked += new System.Windows.RoutedEventHandler(this.CheckBox_Unchecked);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

